# Site
name: "가짜연구소(Pseudo Lab)"
title: "가짜연구소(Pseudo Lab)"
description: "우리는 믿습니다. 열정을 가진 사람들이 세상을 더 나은 곳으로 변화시킬 수 있다고 말이죠."
logo: 'assets/images/Pseudo_Lab_logo.png'
favicon: 'assets/images/Pseudo_Lab_logo.png'
# baseurl: /jekyll-theme-memoirs
# google_analytics: 'UA-xxxxxxxx-1'
disqus: 'demowebsite'
# mailchimp-list: 'https://wowthemes.us11.list-manage.com/subscribe/post?u=8aeb20a530e124561927d3bd8&amp;id=8c3d2d214b'
include: ["_pages"]
permalink: /:title/
email: pseudolab.operator@gmail.com

# Builder
authors:
  김찬란:
    name: 김찬란
    display_name: 김찬란
    avatar: 'assets/images/김찬란.png'
    email: seriousran@gmail.com
    linkedIn: https://www.linkedin.com/in/chanran-kim/
    github: https://github.com/seriousran
    tag: [1기 신약개발대회, 2기 Kaggle Master가 되기 위한 몸부림, 3기 COVID-19, 3기 4차 산업혁명의 찰스 디킨스]
    description: "함께 개발자"
  강민지:
    name: 강민지
    display_name: 강민지
    avatar: 'assets/images/강민지.png'
    email: jaellen000@gmail.com
    linkedIn: https://www.linkedin.com/in/mmminji/
    github: https://github.com/mmminji
    tag: [1-2기 딥러닝 튜토리얼 제작, 3기 Full Stack Deep Learning, 3기 커뮤니티 빌더]
    description: "배우고 싶은 사람1"
  김지연:
    name: 김지연
    display_name: 김지연
    avatar: 'assets/images/김지연.png'
    email: rlawldusgus@gmail.com
    # linkedIn: 
    github: https://github.com/jsjyk
    tag: [3기 GraphML, 3기 커뮤니티 빌더]
    description: "다양한 경험을 추구하는"
  심석보:
    name: 심석보
    display_name: 심석보
    avatar: 'assets/images/심석보.png'
    email: seokbo96@gmail.com
    # linkedIn: 
    # github: 
    tag: [3기 커뮤니티 빌더]
    description: "최선을 다해서!"

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
  - jekyll-figure
    
# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'
    
# Pagination 
paginate: 6
paginate_path: /page:num/
    
# Other
highlighter: rouge
markdown: kramdown
kramdown:
   syntax_highlighter_opts:
      disable : true



# Adsense (change to "enabled" to activate, also your client id and ad slot. Create a new ad unit from your Adsense account to get the slot.)
adsense: "disabled"
adsense-data-ad-client: "ca-pub-3412143450191416"
adsense-data-ad-slot: "1363087678"

# Lazy Images ("enabled" or "disabled")
lazyimages: "disabled"

# Post Author Box ("enabled" or "disabled")
authorbox: "enabled"

# Sass
sass:
  sass_dir: _sass
  style: compressed

exclude: [changelog.md, LICENSE.txt, README.md, Gemfile, Gemfile.lock]
