# Site
name: "가짜연구소(Pseudo Lab)"
title: "가짜연구소(Pseudo Lab)"
description: "가짜연구소 블로그"
sub-description: "우리는 믿습니다. 열정을 가진 사람들이 세상을 더 나은 곳으로 변화시킬 수 있다고 말이죠."
logo: 'assets/images/Pseudo_Lab_logo.png'
favicon: 'assets/images/Pseudo_Lab_logo.png'
# baseurl: /jekyll-theme-memoirs
google_analytics: 'UA-185350287-2'
disqus: 'demowebsite'
# mailchimp-list: 'https://wowthemes.us11.list-manage.com/subscribe/post?u=8aeb20a530e124561927d3bd8&amp;id=8c3d2d214b'
include: ["_pages"]
permalink: /:title/
email: pseudolab.operator@gmail.com
url : "https://pseudolab.github.io/"

# Builder
authors:
  강민지:
    name: 강민지
    display_name: 강민지
    avatar: 'assets/images/builder-profile/강민지.png'
    email: jaellen000@gmail.com
    linkedIn: https://www.linkedin.com/in/mmminji/
    github: https://github.com/mmminji
    tag: [LGCNS 비전AI사업팀, Data Scientist, Computer Vision]
    description: "/ 1-4기 / 홍익인간; 세상을 널리 이롭게 하라"
  김소연:
    name: 김소연
    display_name: 김소연
    avatar: 'assets/images/builder-profile/김소연.png'
    email: kimcando94@gmail.com
    linkedIn: https://www.linkedin.com/in/soyeon-kim-733107168/
    github: https://github.com/kimcando
    tag: [LG AI, NLP, Federated learning]
    description: "/ 3-4기 / Think globally, act locally."
  김지연:
    name: 김지연
    display_name: 김지연
    avatar: 'assets/images/builder-profile/김지연.png'
    email: rlawldusgus@gmail.com
    linkedIn: https://www.linkedin.com/in/jiyeon-kim-6509a01b6/
    github: https://github.com/jsjyk
    tag: [석사막학기, SystemBiology]
    description: "/ 2-4기 / 다양한 경험을 추구하는"
  김찬란:
    name: 김찬란
    display_name: 김찬란
    avatar: 'assets/images/builder-profile/김찬란.png'
    email: seriousran@gmail.com
    linkedIn: https://www.linkedin.com/in/chanran-kim/
    github: https://github.com/seriousran
    tag: [SK텔레콤, HP 글로벌 앰버서더, 디저트 중독]
    description: "/ 1-8기 / 함께 개발자"
  신진수:
    name: 신진수
    display_name: 신진수
    avatar: 'assets/images/builder-profile/신진수.png'
    email: jsshin2013@gmail.com
    linkedIn: https://kr.linkedin.com/in/jinsoo-shin-436060162
    github: https://github.com/jsshin2019
    tag: [크래프톤, Network Science, 이상탐지]
    description: "/ 8기 / SHOW ME THE DATA"
  심석보:
    name: 심석보
    display_name: 심석보
    avatar: 'assets/images/builder-profile/심석보.png'
    email: seokbo96@gmail.com
    # linkedIn: 
    github: https://github.com/tonyya21
    tag: [석박통합생, Systembiology]
    description: "/ 3-4기 / 최선을 다하는"
  안성진:
    name: 안성진
    display_name: 안성진
    avatar: 'assets/images/builder-profile/안성진.jpg'
    # email: 
    # linkedIn: 
    github: https://github.com/SDSTony
    tag: [Microsoft]
    description: "/ 1-7기 / "
  이정훈:
    name: 이정훈
    display_name: 이정훈
    avatar: 'assets/images/builder-profile/이정훈.png'
    email: vhrehfdl@gmail.com
    linkedIn: https://www.linkedin.com/in/%EC%A0%95%ED%9B%88-%EC%9D%B4-00b282129/
    github: https://github.com/vhrehfdl
    tag: [인터파크 톡집사 개발팀, NLP, MLOps, Story NLP]
    description: "/ 3-6기 / Positive mind"
  한수민:
    name: 한수민
    display_name: 한수민
    avatar: 'assets/images/builder-profile/한수민.png'
    email: etckoko@gmail.com
    # linkedIn: 
    # github: https://github.com/suojoah
    tag: [Graph ML, GNN, Network Analysis]
    description: "/ 1-7기 / No limits"
  김정훈:
    name: 김정훈
    display_name: 김정훈
    avatar: 'assets/images/builder-profile/김정훈.jpg'
    email: seriousran@gmail.com
    linkedIn: https://www.linkedin.com/in/jj150618/
#    github:
    tag: [ IHFB ]
    description: "/ 8기 / Comeback"
  임진우:
    name: 임진우
    display_name: 임진우
    avatar: 'assets/images/builder-profile/한수민.png'
    email: jinwooiminha@gmail.com
    # linkedIn: www.linkedin.com/in/jinwoo-im-589a5a287
    # github: https://github.com/AEInha
    tag: [Undergraduate students]
    description: "/ 1-7기 / 로켓같은 삶"
# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
  - jekyll-figure
    
# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'
    
# Pagination 
paginate: 6
paginate_path: /page:num/
    
# Other
highlighter: rouge
markdown: kramdown
kramdown:
   syntax_highlighter_opts:
      disable : true
future: true


# Adsense (change to "enabled" to activate, also your client id and ad slot. Create a new ad unit from your Adsense account to get the slot.)
adsense: "disabled"
adsense-data-ad-client: "ca-pub-3412143450191416"
adsense-data-ad-slot: "1363087678"

# Lazy Images ("enabled" or "disabled")
lazyimages: "disabled"

# Post Author Box ("enabled" or "disabled")
authorbox: "enabled"

# Sass
sass:
  sass_dir: _sass
  style: compressed

exclude: [changelog.md, LICENSE.txt, README.md, Gemfile, Gemfile.lock]
