# Site
name: "가짜연구소(Pseudo Lab)"
title: "가짜연구소(Pseudo Lab)"
description: "가짜연구소(Pseudo Lab)"
logo: 'assets/images/about.png'
favicon: 'assets/images/Pseudo_Lab_logo.png'
# baseurl: /jekyll-theme-memoirs
# google_analytics: 'UA-xxxxxxxx-1'
disqus: 'demowebsite'
# mailchimp-list: 'https://wowthemes.us11.list-manage.com/subscribe/post?u=8aeb20a530e124561927d3bd8&amp;id=8c3d2d214b'
include: ["_pages"]
permalink: /:title/
email: pseudolab.operator@gmail.com

# Authors
authors:
  김찬란:
    name: 김찬란
    display_name: 김찬란
    # avatar: 'assets/images/강민지.png'
    # email: jaellen000@gmail.com
    # linkedIn: https://www.linkedin.com/in/mmminji/
    # github: https://github.com/mmminji
    description: "가짜연구소 빌더"
  강민지:
    name: 강민지
    display_name: 강민지
    avatar: 'assets/images/강민지.png'
    email: jaellen000@gmail.com
    linkedIn: https://www.linkedin.com/in/mmminji/
    github: https://github.com/mmminji
    tag: [1-2기 딥러닝 튜토리얼 제작, 3기 Full Stack Deep Learning]
    description: "배우고 싶은 개발자"
  # john:
  #   name: John
  #   display_name: John    
  #   avatar: 'assets/images/avatar.png'
  #   email: wowthemesnet@gmail.com
  #   web: https://www.wowthemes.net
  #   twitter: https://twitter.com/wowthemesnet
  #   description: "Write a short description of the author here. You are currently previewing Memoirs demo, a Jekyll template compatible with Github pages."

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
  - jekyll-figure
    
# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'
    
# Pagination 
paginate: 6
paginate_path: /page:num/
    
# Other
highlighter: rouge
markdown: kramdown
kramdown:
   syntax_highlighter_opts:
      disable : true



# Adsense (change to "enabled" to activate, also your client id and ad slot. Create a new ad unit from your Adsense account to get the slot.)
adsense: "disabled"
adsense-data-ad-client: "ca-pub-3412143450191416"
adsense-data-ad-slot: "1363087678"

# Lazy Images ("enabled" or "disabled")
lazyimages: "disabled"

# Post Author Box ("enabled" or "disabled")
authorbox: "enabled"

# Sass
sass:
  sass_dir: _sass
  style: compressed

exclude: [changelog.md, LICENSE.txt, README.md, Gemfile, Gemfile.lock]
